# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: vmss-win2019-ado-hub-predev

jobs:
  - job: Test
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Write your commands here
      
          echo Hello world
    - task: IISWebAppDeploymentOnMachineGroup@0
      inputs:
        WebSiteName: 'test'
        Package: '$(System.DefaultWorkingDirectory)\**\*.zip'