
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: vmss-ado-hub-prod
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acr-tkdata-comn-prod'
    command: 'login'
    addPipelineData: false
    addBaseImageData: false
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      nslookup desprodcontainers.azurecr.io
      curl -k -vvvv -o image.tar desprodcontainers.privatelink.azurecr.io/des-cicd/des_cicd_pipeline_img:latest
      ls -l
     #docker login desprodcontainers.azurecr.io
      #echo 'Hello world'
      #az --version
      #python --version
      #docker --version
      #sqlcmd
      #pwsh --version
      #python3 --version
